version: "3.8"
services:
  mysql:
    image: mysql:8.0 
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_unilunch
      MYSQL_USER: user_unilunch
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql # Persistencia de datos
    ports:
      - "3307:3306" #Puertos de la base de datos